export const ROUTES = {
  HOME: '/',
  LOGIN: '/login',
  DASHBOARD: '/dashboard',
  ENQUIRIES: '/enquiries',
  PRODUCTS: '/products',
  CATEGORIES: '/categories',
  BRANDS: '/brands',
  HOMEPAGE: '/homepage',
  CONTACTS: '/contacts',
  NOTIFICATIONS: '/notifications',
  USERS: '/users',
  SETTINGS: '/settings',
  FORBIDDEN: '/forbidden',
};
